### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by niclasnilsson** [jasongilman/proto-repl-charts#17]
When running the first example from the docs:

```
(proto-repl-charts.charts/line-chart
 "Trigonometry"
 {"sin" (map #(Math/sin %) (range 0.0 6.0 0.2))
  "cos" (map #(Math/cos %) (range 0.0 6.0 0.2))})
```

the error below occurs. But - it doesn't happen the first time I execute it, only when I execute it the second time (and third, ...). 

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [proto-repl-charts](https://github.com/jasongilman/proto-repl-charts) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'value' of null

```
At /Users/nicke/.atom/packages/proto-repl-charts/node_modules/jg-c3/c3.js:3864

TypeError: Cannot read property 'value' of null
    at /packages/proto-repl-charts/node_modules/jg-c3/c3.js:3864:56
    at Array.sort (native)
    at ChartInternal.c3_chart_internal_fn.getTooltipContent (/packages/proto-repl-charts/node_modules/jg-c3/c3.js:3863:15)
    at ChartInternal.tooltip_contents (/packages/proto-repl-charts/node_modules/jg-c3/c3.js:1273:54)
    at ChartInternal.c3_chart_internal_fn.showTooltip (/packages/proto-repl-charts/node_modules/jg-c3/c3.js:3947:49)
    at /packages/proto-repl-charts/node_modules/jg-c3/c3.js:2481:24)
    at SVGRectElement.__onmousemove (/packages/proto-repl-charts/node_modules/d3/d3.js:1120:18)
```

### Commands

```
     -1:52 proto-repl:execute-top-block (input.hidden-input)
  6x -1:42.7.0 vim-mode-plus:move-right (input.hidden-input)
     -1:41.2.0 vim-mode-plus:replace-character (input.hidden-input)
     -1:41 vim-mode-plus:set-input-char-1 (input.hidden-input)
  2x -1:40.4.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -1:39.1.0 proto-repl:execute-top-block (input.hidden-input)
     -1:31.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:26.4.0 vim-mode-plus:move-up (input.hidden-input)
     -1:24.5.0 proto-repl:execute-top-block (input.hidden-input)
     -1:22.6.0 proto-repl:toggle (input.hidden-input)
  2x -1:22.4.0 autocomplete-plus:cancel (atom-text-editor.editor)
     -1:17 proto-repl:execute-top-block (input.hidden-input)
  3x -1:17 autocomplete-plus:cancel (atom-text-editor.editor)
     -1:15.5.0 bracket-matcher:go-to-matching-bracket (div.proto-repl-charts-chart.native-key-bindings)
  2x -1:14.8.0 core:cancel (div.proto-repl-charts-chart.native-key-bindings)
     -1:11.8.0 proto-repl:execute-top-block (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
atom-dark-fusion-syntax 2.2.0 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-mdtoc 0.8.3 
atomatigit 1.5.5 
autocomplete-paths 1.0.5 
autoupdate-packages 1.3.1 
blame 0.10.3 
busy 0.7.0 
busy-signal 1.3.0 
easy-motion-redux 1.1.1 
environment 1.3.1 
ex-mode 0.14.0 
expand-region 0.2.6 
file-icons 2.1.2 
file-watcher 1.1.0 
git-history 3.3.0 
git-plus 7.3.3 
golden-ratio 0.3.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
ink 0.6.5 
intentions 1.1.2 
language-diff 0.7.0 
lines 0.13.1 
linter 2.1.2 
linter-clojure 1.1.3 
linter-markdown 3.1.0 
linter-ui-default 1.2.2 
markdown-preview-enhanced 0.10.11 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.4 
maximize-panes 0.2.0 
merge-conflicts 1.4.4 
move-panes 0.2.0 
nucleus-dark-ui 0.11.0 
Parinfer 1.17.0 
project-plus 0.9.0 
proto-repl 1.4.18 
proto-repl-charts 0.4.0 
proton-mode 0.15.0 
recent-files-fuzzy-finder 0.3.1 
relative-numbers 0.7.1 
release-notes 0.53.0 
tab-switcher 1.5.4 
theme-switch 0.4.0 
vim-mode-plus 0.85.1 
vim-mode-plus-ex-mode 0.9.0 
wordcount 2.10.4 
zentabs 0.8.8 
```

**Comment by FaisalDirieA** [comment]
If you close the chart tab, and run again, you won't see the error. This error only happens if one reruns while the previous chart is still open. By closing the "Trignometry" chart tab, you can rerun and wont see the error.
That is my observation.
