### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by ghost** [jasongilman/proto-repl-charts#2]
[Enter steps to reproduce below:]
1. Execute following code in proto-repl:

``` clojure
(require 'prc)
(defn f [x] (* x x))
(prc/line-chart "My F" {"f" (map f (range 0.0 0.6 0.2))})
```
1. See that a blank (white) page is shown instead of any chart.
2. Execute the last line again.
3. See the red box displayed by Atom: "Uncaught Error: Module did not self-register."

**Atom Version**: 1.5.3
**System**: Ubuntu 14.04.4
**Thrown From**: [proto-repl-charts](https://github.com/jasongilman/proto-repl-charts) package, v0.1.0
### Stack Trace

Uncaught Error: Module did not self-register.

```
At events.js:141

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at bindings (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/node_modules/d3/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/node_modules/d3/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:113)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/node_modules/d3/node_modules/jsdom/lib/jsdom/browser/index.js:14:21)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/node_modules/d3/node_modules/jsdom/lib/jsdom.js:11:20)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/node_modules/d3/index.js:1:95)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at new ChartInternal (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/c3.js:49:74)
  at new Chart (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/c3.js:32:34)
  at Object.c3.generate (@HOME@/.atom/packages/proto-repl-charts/node_modules/c3/c3.js:58:16)
  at ChartView.module.exports.ChartView.display (@HOME@/.atom/packages/proto-repl-charts/lib/chart-view.coffee:35:19)
  at Object.module.exports.ProtoReplCharts.display (@HOME@/.atom/packages/proto-repl-charts/lib/proto-repl-charts.coffee:65:14)
  at @HOME@/.atom/packages/proto-repl-charts/lib/proto-repl-charts.coffee:27:12
  at @HOME@/.atom/packages/proto-repl/lib/repl.coffee:279:11
  at @HOME@/.atom/packages/proto-repl/lib/repl.coffee:168:11
  at Transform.msgHandler (@HOME@/.atom/packages/proto-repl/node_modules/jg-nrepl-client/src/nrepl-client.js:130:21)
  at emitOne (events.js:77:13)
  at Transform.emit (events.js:169:7)
  at @HOME@/.atom/packages/proto-repl/node_modules/jg-nrepl-client/src/nrepl-client.js:103:9
  at Array.forEach (native)
  at consumeNreplMessageStream (@HOME@/.atom/packages/proto-repl/node_modules/jg-nrepl-client/src/nrepl-client.js:101:28)
  at Transform.messageStream._transform (@HOME@/.atom/packages/proto-repl/node_modules/jg-nrepl-client/src/nrepl-client.js:75:38)
  at Transform._read (_stream_transform.js:167:10)
  at Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:292:12)
  at writeOrBuffer (_stream_writable.js:278:5)
  at Transform.Writable.write (_stream_writable.js:207:11)
  at Socket.ondata (_stream_readable.js:525:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)

```
### Commands

```
     -1:04.7.0 proto-repl:toggle (atom-text-editor.editor.is-focused)
     -0:59.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:57.1.0 proto-repl:execute-text-entered-in-repl (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:50 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:44.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:44.1.0 proto-repl:execute-text-entered-in-repl (atom-text-editor.editor.is-focused)
  6x -0:38.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:30.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:14.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:13.8.0 proto-repl:execute-text-entered-in-repl (atom-text-editor.editor.is-focused)
     -0:04.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:03.5.0 core:copy (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.2.0 proto-repl:execute-text-entered-in-repl (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.14.0
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.15.4
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-hy, v0.1.0
language-ini, v1.14.0
language-latex, v0.6.1
language-lua, v0.9.4
language-nftables, v0.2.1
language-ocaml, v1.1.2
language-opencl, v0.1.1
language-rust, v0.4.6
language-thrift, v1.0.2
language-tmux, v0.4.0
latex, v0.29.0
latexer, v0.3.0
linter, v1.11.3
linter-clang, v3.4.4
linter-clojure, v1.1.2
linter-csslint, v1.3.1
linter-gcc, v0.6.7
linter-glsl, v1.0.6
linter-htmlhint, v1.0.3
linter-lua, v1.0.1
linter-luacheck, v1.1.4
linter-php, v1.1.8
linter-rust, v0.4.1
linter-tidy, v2.1.0
minimap, v4.19.0
nuclide, v0.119.0
pdf-view, v0.39.0
project-manager, v2.7.6
proto-repl, v0.15.2
proto-repl-charts, v0.1.0
tool-bar, v0.2.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by jasongilman** [comment]
Can you try updating to the latest version of proto repl charts and then restarting atom to see if that resolves the issue?

**Comment by ghost** [comment]
Great! It works now. Thanks for fixing this so quickly!
